# Generated by Django 3.0.6 on 2020-06-12 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.TextField()),
                ('option1', models.CharField(max_length=100, null=True)),
                ('option2', models.CharField(max_length=100, null=True)),
                ('option3', models.CharField(max_length=100, null=True)),
                ('option4', models.CharField(max_length=100, null=True)),
                ('correct', models.CharField(max_length=100, null=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='namo.Subject')),
            ],
        ),
    ]
