# Generated by Django 3.0.6 on 2020-06-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='info',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
