# Generated by Django 3.0.6 on 2020-06-16 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namo', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subjects',
        ),
    ]
