# Generated by Django 3.0.6 on 2020-06-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namo', '0005_auto_20200617_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/profile/default.png', null=True, upload_to='images/profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, to='namo.Subject'),
        ),
    ]
