# Generated by Django 3.0.6 on 2020-06-17 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namo', '0006_auto_20200617_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
