# Generated by Django 3.0.6 on 2020-06-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namo', '0007_remove_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
