# Generated by Django 3.0.6 on 2020-06-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namo', '0008_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('pic', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
                ('comt', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
