# Generated by Django 3.0.6 on 2020-06-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namo', '0010_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='comt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
