# Generated by Django 3.0.6 on 2020-06-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namo', '0012_auto_20200618_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pic',
        ),
    ]
