# Generated by Django 3.0.6 on 2020-06-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namo', '0015_auto_20200618_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, default='{% static "images/default.png" %}', null=True, upload_to=''),
        ),
    ]
