# Generated by Django 3.0.6 on 2020-06-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namo', '0021_auto_20200618_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
