# Generated by Django 3.0.6 on 2020-06-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namo', '0022_auto_20200618_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='note',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
